### ISSUE TITLE
Add README file & explain how to run project with grunt and/or cordova

### ISSUE THREAD

**Issue by cmoulliard** [feedhenry-templates/blank-cordova-app#5]
As Feedhenry documentation refers to this template to create a feedhenry - cordova client, it should be interesting to have a README file explaining how to use it, create the cordova project for ios, android and/or browser platforms and how to run it using grunt serve:local --platform:ios

**Comment by nirzari18** [comment]
Read me would be really helpful!!

**Comment by david-martin** [comment]
This template is now deprecated in favour of https://github.com/feedhenry-templates/helloworld-app
Please consider re-opening this issue there.
